services:
  pipeline-doctor-api:
    build: .
    image: pipeline-doctor-api:1.0

    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"

    ports:
      - "8080:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      OLLAMA_URL: "http://host.docker.internal:11434/api/chat"
      MODEL: "qwen2.5-coder:7b"
      OUTPUT_FILE: "/output/pipeline_analysis.json"

    volumes:
      - "./output:/output"